"""The hashing text embedding, mirrored from TypeScript.

The point of duplicating it is that both sides must produce identical vectors:
an index built by one and queried by the other has to land in the same space, or
search silently returns noise. `tests/test_hashing.py` checks this against
vectors generated by the TypeScript implementation, so the two cannot drift
apart unnoticed.

Be clear about what it is: lexical retrieval, not semantic. It finds the words
that are there. Its job is to make search work on a machine with no model at
all, and to be replaced the moment one is configured.
"""

from __future__ import annotations

import math
import re
import unicodedata

DEFAULT_DIM = 256
DEFAULT_NGRAMS = (2, 3)

_PUNCTUATION = re.compile(r"[^\w\s]|_", re.UNICODE)
_WHITESPACE = re.compile(r"\s+")


def normalize_text(text: str) -> str:
    """Folds width and case, and reduces punctuation to single spaces."""
    folded = unicodedata.normalize("NFKC", text).lower()
    folded = _PUNCTUATION.sub(" ", folded)
    return _WHITESPACE.sub(" ", folded).strip()


def fnv1a(value: str) -> int:
    """FNV-1a, 32 bit, over UTF-16 code units low byte first.

    The byte order matters: this has to match the TypeScript implementation
    exactly, and JavaScript strings are UTF-16.
    """
    hash_value = 0x811C9DC5
    for char in value:
        code = ord(char)
        if code > 0xFFFF:
            # Astral characters are two UTF-16 code units in JavaScript, so they
            # have to be hashed as the surrogate pair to match.
            adjusted = code - 0x10000
            units = [0xD800 + (adjusted >> 10), 0xDC00 + (adjusted & 0x3FF)]
        else:
            units = [code]
        for unit in units:
            hash_value ^= unit & 0xFF
            hash_value = (hash_value * 0x01000193) & 0xFFFFFFFF
            high = unit >> 8
            if high:
                hash_value ^= high
                hash_value = (hash_value * 0x01000193) & 0xFFFFFFFF
    return hash_value & 0xFFFFFFFF


def embed(
    text: str, dim: int = DEFAULT_DIM, ngrams: tuple[int, ...] = DEFAULT_NGRAMS
) -> list[float]:
    vector = [0.0] * dim
    counts: dict[str, int] = {}
    for feature in _features(text, ngrams):
        counts[feature] = counts.get(feature, 0) + 1

    for feature, count in counts.items():
        # Sublinear term frequency: a word said ten times is not ten times more
        # about the topic than a word said once.
        weight = 1 + math.log(count)
        index = fnv1a(feature) % dim
        # Signed hashing, so collisions cancel instead of always adding up.
        sign = 1 if (fnv1a(f"{feature}#sign") & 1) == 0 else -1
        vector[index] += sign * weight

    return l2normalize(vector)


def l2normalize(vector: list[float]) -> list[float]:
    total = sum(value * value for value in vector)
    if total == 0:
        return vector
    norm = math.sqrt(total)
    return [value / norm for value in vector]


def _features(text: str, ngrams: tuple[int, ...]):
    normalized = normalize_text(text)
    if not normalized:
        return

    for word in normalized.split(" "):
        if word:
            yield f"w:{word}"

    compact = normalized.replace(" ", "")
    for n in ngrams:
        if len(compact) < n:
            continue
        for i in range(len(compact) - n + 1):
            yield f"c{n}:{compact[i : i + n]}"
