/**
 * Freezes what the worked example compiles and plans to.
 *
 * Determinism is only useful if somebody looks at it. This writes a compact
 * summary of the analysis and of two cuts, so a change to segmentation, scoring,
 * skills or planning shows up as a reviewable diff rather than as a number
 * nobody compared. It is the difference between "the tests still pass" and "the
 * cut is still the cut".
 *
 * Regenerate with `pnpm golden:update`, and read the diff before committing it.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { compileProject } from '@editorial-ir/core';
import { HeuristicDecisionBackend } from '@editorial-ir/decision';
import { SkillRegistry } from '@editorial-ir/skills';
import { planEdit, reviewPlan } from '@editorial-ir/agent';
import { formatTimecode, operationTimelineDuration, planDurationMs } from '@editorial-ir/contracts';
import { exampleSuite, makeExampleProject } from '../tests/support/project.js';

export interface Golden {
  note: string;
  analysis: {
    events: number;
    chapters: number;
    relations: number;
    utterances: number;
    mean_event_seconds: number;
    chapters_named: string[];
  };
  cuts: Record<string, CutSummary>;
}

export interface CutSummary {
  clips: number;
  duration: string;
  duration_error_seconds: number;
  events_selected: number;
  events_available: number;
  mean_clip_seconds: number;
  mean_importance: number;
  review_observations: number;
  timeline: string[];
}

export async function buildGolden(): Promise<Golden> {
  const store = await makeExampleProject();
  const { ir, observations } = await compileProject({
    store,
    suite: exampleSuite(),
    decision: new HeuristicDecisionBackend(),
  });
  const registry = SkillRegistry.withBuiltIns();

  const cuts: Record<string, CutSummary> = {};
  for (const [skill, seconds] of [
    ['travel-vlog', 180],
    ['shorts', 40],
    ['memory-film', 240],
  ] as const) {
    const plan = planEdit({
      ir,
      skill: registry.resolve(skill),
      targetDurationMs: seconds * 1000,
      observations,
    });

    cuts[skill] = {
      clips: plan.stats.operation_count,
      duration: formatTimecode(planDurationMs(plan), false),
      duration_error_seconds: Math.round(plan.stats.duration_error_ms / 100) / 10,
      events_selected: plan.stats.events_selected,
      events_available: plan.stats.events_available,
      mean_clip_seconds:
        Math.round(
          plan.tracks.video.reduce((sum, o) => sum + operationTimelineDuration(o), 0) /
            Math.max(1, plan.tracks.video.length) /
            100,
        ) / 10,
      mean_importance: plan.stats.mean_importance,
      review_observations: reviewPlan(plan, ir).length,
      // The cut itself, one line per clip. This is the part worth reading in a
      // diff: it is where "the numbers are the same but the edit changed" shows.
      timeline: plan.tracks.video.map((operation) => {
        const event = ir.events.find((e) => e.id === operation.event_id);
        const length = (Math.round(operationTimelineDuration(operation) / 100) / 10).toFixed(1);
        return `${operation.operation_id} ${length.padStart(5)}s ${(operation.role ?? '-').padEnd(11)} ${
          event?.description.value.slice(0, 44) ?? ''
        }`;
      }),
    };
  }

  return {
    note: 'Generated by scripts/make-golden.ts. Read the diff; do not just regenerate it.',
    analysis: {
      events: ir.stats.event_count,
      chapters: ir.stats.chapter_count,
      relations: ir.stats.relation_count,
      utterances: ir.stats.utterance_count,
      mean_event_seconds: Math.round(ir.stats.mean_event_duration_ms / 100) / 10,
      chapters_named: ir.chapters.map((chapter) => chapter.title.value),
    },
    cuts,
  };
}

export const GOLDEN_PATH = fileURLToPath(new URL('../tests/golden/example.json', import.meta.url));

// `pnpm golden:update` passes --write. Importing this file for its builder must
// not rewrite the file the tests are about to compare against.
if (process.argv.includes('--write')) {
  const golden = await buildGolden();
  writeFileSync(GOLDEN_PATH, `${JSON.stringify(golden, null, 2)}\n`);
  console.log(`wrote ${GOLDEN_PATH}`);
}
