/**
 * Writes the cross-language contract test for the hashing text embedding.
 *
 * Both runtimes implement it, and both have to produce identical vectors: an
 * index built by one and queried by the other must land in the same space, or
 * search silently returns noise. This freezes the TypeScript output so the
 * Python test can assert against it.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { HashingTextEmbedding, fnv1a, normalizeText } from '@editorial-ir/perception';

const SAMPLES = [
  '',
  'hello world',
  'やっと着いた！',
  'UNIVERSAL STUDIOS JAPAN',
  'ＵＳＪの入口に到着した',
  'Tom & Jerry, 2026',
  '夜景がきれい',
  'a',
  '   spaced   out   ',
  'ramen ramen ramen bowl',
  'emoji 🎢 ride',
];

const model = new HashingTextEmbedding();
const golden = {
  note: 'Generated by scripts/make-hashing-golden.ts. Do not edit by hand.',
  dim: model.dim,
  normalize: Object.fromEntries(SAMPLES.map((text) => [text, normalizeText(text)])),
  fnv1a: Object.fromEntries(
    [...SAMPLES, 'c2:夜景', 'w:hello', 'hello#sign'].map((text) => [text, fnv1a(text)]),
  ),
  vectors: Object.fromEntries(
    SAMPLES.map((text) => [text, model.embedOne(text).map((v) => Math.round(v * 1e9) / 1e9)]),
  ),
};

const out = fileURLToPath(
  new URL('../services/perception/tests/hashing_golden.json', import.meta.url),
);
writeFileSync(out, `${JSON.stringify(golden, null, 2)}\n`);
console.log(`wrote golden vectors for ${SAMPLES.length} samples`);
